# Generated by Django 2.1.7 on 2019-05-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190516_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirant',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote',
        ),
        migrations.AddField(
            model_name='vote',
            name='aspirant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Aspirant'),
        ),
        migrations.AddField(
            model_name='vote',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Position'),
        ),
    ]
